version: '3.4'

networks:
  user:
  service:

services:
  service.api:
    image: ${DOCKER_REGISTRY-}serviceapi
    build:
      context: .
      dockerfile: MicroServices/APIs/Service/Service.Api/Dockerfile
    depends_on:
      - service.db
    networks:
      - service
  
  service.db:
    container_name: servicedb
    image: mysql
    networks:
      - service
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: accountowner
        MYSQL_USER: dbservice
        MYSQL_PASSWORD: dbservicepasswordd
    restart: always
    ports:
      - "3307:3306"

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: MicroServices/APIs/User/User.Api/Dockerfile
    depends_on:
      - user.db
    networks: 
      - user

  user.db:
    container_name: userdb 
    image: mysql
    networks:
      - user
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: accountowner
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbuserpasswordd
    restart: always
    ports:
      - "3306:3306"
